# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150)),
                ('Synopsis', models.TextField()),
                ('Date', models.DateTimeField(verbose_name='Published On')),
                ('Number', models.SmallIntegerField(unique=True)),
                ('SoundCloud', models.CharField(default='', max_length=2000)),
            ],
        ),
    ]
