# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CastMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Photo', models.ImageField(default='cast_images/loser.jpg', upload_to='cast_images')),
                ('Bio', models.TextField()),
                ('Silhouette', models.ImageField(default='cast_images/imabear.png', upload_to='cast_images')),
                ('CharacterName', models.TextField(max_length=100)),
                ('CharacterBio', models.TextField()),
                ('slug', models.CharField(max_length=128, unique=True)),
            ],
        ),
    ]
